version: "3"
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/app
    command:
      [
        "start_server",
        "--port",
        "80",
        "--",
        "plackup",
        "-I",
        "src/",
        "-s",
        "Gazelle",
        "-E",
        "development",
        "app.psgi",
      ]
